name: Run integration tests

on:
  pull_request:

jobs:
  integrationtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - run: docker build --load -t helmfile-nix .
      - name: Create KIND Cluster
        uses: helm/kind-action@06c1ae10762d3b9c1644e7fe69596ae519e015a2 # v1.15.0
        with:
          kubeconfig: ./kubeconfig
      - run: kubectl cluster-info --context kind-chart-testing --kubeconfig kubeconfig
      - run: docker run --network=host -v .:/app -e KUBECONFIG=/app/kubeconfig helmfile-nix apply -f /app/testData/helm-nixchart
      - run: docker run --network=host -v .:/app -e KUBECONFIG=/app/kubeconfig helmfile-nix diff -f /app/testData/helm-nixchart
